### ISSUE TITLE
Any difference between luar and luna?

### ISSUE THREAD

**Issue by guijun** [beatgammit/luna#6]
https://github.com/stevedonovan/luar.

I'm confused and I'm wondering which should I use.

**Comment by beatgammit** [comment]
I made `luna` before I found `luar`, and I personally like the API I made. They're both meant to be relatively thin wrappers to [golua](https://github.com/aarzilli/golua), but since I've only briefly looked at `luar`, so I don't know what exactly it offers.

`luar` is more popular than `luna`, but I think that has more to do with `luar` being mentioned in the `golua` README than anything. I haven't made any effort to advertise it, and I don't have a lot of examples available, but those ore on the TODO list.

`luna` also isn't _done_. It passes tests and seems to work, but there are plenty of things that need to be done before I'm ready to recommend it for anything but experimentation. For example:
- update to work with lua 5.2 (and offer both options)
- support sending methods to Lua (currently, only struct data is sent)
- support writable data types (currently, everything's read-only)
- allow sending more types from Lua to Go (e.g. functions)

That being said, a lot of things work, such as sending nearly any data type (structs, maps, slices, etc.), registering functions and overriding `stdout` (to an extent), etc. I've just added locking, so `luna` _should_ be thread-safe (needs a good test). I haven't tested anything exotic, but the basics seem to work pretty well.

If you decide to use `luna`, be sure to open issues for anything you need/would like. Once I feel a bit more comfortable with the state of things, I'll probably advertise on the `go-nuts` mailing list, `reddit`, etc.
